on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
   
    - name: Build
      run: dotnet build --configuration Release 
    - name: Test
      run: dotnet test --configuration Release  --no-build
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output .
    - name: Push
      run: dotnet nuget push MyLearningCLib.nupkg --source https://nuget.pkg.github.com/patric1305/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
